# Build customization
builds:
  - main: ./cmd/csv2tsprofile
    binary: csv2tsprofile
    goos:
      - linux
    goarch:
      - amd64
  - main: ./cmd/tspredictor
    binary: tspredictor
    goos:
      - linux
    goarch:
      - amd64      

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  vendor: Christopher B. Hauser
  homepage: https://cha87de.github.io/tsprofiler/
  maintainer: Christopher B. Hauser <post@c-ha.de>
  description: a profiler for time series data - integrates well in kvmtop
  license: GPL-3.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin
